AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'
    - 'config/**/*.rb'

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 20
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/WordArray:
  Enabled: true
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Enabled: true
  Exclude:
    - 'db/schema.rb'

Style/SymbolArray:
  Enabled: true
  Exclude:
    - 'config/routes.rb'

Layout/EmptyLineAfterMagicComment:
  Enabled: false