AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'bin/bundle'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false